# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# Setup
title:        CyberQuest
# Uncomment if you need a description, this one is a bit lengthy
# description: >- 
#   A game to teach children and their parents ...
tagline:      Cyber awareness game for children and parents
domain: cyberquestgame.github.io/
url: https://cyberquestgame.github.io/
# description: Cyber awareness game for children and parents
show_downloads: false
theme: jekyll-cayman

paginate:     1
locale:       "en"
# google_analytics: [Your Google Analytics tracking ID]

# About/contact
author:
  name:       Dr. Asma Adnane
  url:        https://www.lboro.ac.uk/departments/compsci/staff/asma-adnane/

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown

plugins: [jekyll-paginate]

remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme  # Required for GitHub Pages
  
github:
  is_user_page: true
  is_project_page: false
  owner_url: https://github.com/asmaadnane
  owner_name: Asmaadnane
  owner_gravatar_url: /assets/images/octocat.png